trigger: none
pool: window-agent
parameters:
  - name: environment
    default: dev
    values:
      - dev
      - qa
      - prod

stages:
  - stage: terraform_install_init
    displayName: terraform_install_init
    jobs:
      - job: 
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTask@5
            displayName: terraform_init
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)\envirerment\dev'
              backendServiceArm: 'window-vm'
              backendAzureRmStorageAccountName: 'bigbasketcompany'
              backendAzureRmContainerName: 'big'
              backendAzureRmKey: 'qa.tf'
  - stage: terraform_plan
    displayName: terraform plan
    dependsOn: terraform_install_init
    jobs:
      - job: terraform_plan
        steps:
          - task: TerraformTask@5
            displayName: terraform_plan
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(System.DefaultWorkingDirectory)\envirerment\dev'
              environmentServiceNameAzureRM: 'window-vm'
