trigger: none
pool: window-agent
parameters:
  - name: environment
    default: dev
    values:
      - dev
      - qa
      - prod

stages:
  - stage: terraform_install_init
    displayName: terraform_install_init
    jobs:
      - job: 
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTask@5
            displayName: terraform_init
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)\envirerment\dev'
              backendServiceArm: 'window-vm'
              backendAzureRmStorageAccountName: 'bigbasketcompany'
              backendAzureRmContainerName: 'big'
              backendAzureRmKey: 'qa.tf'
  - stage: terraform_plan
    displayName: terraform plan
    dependsOn: terraform_install_init
    jobs:
      - job: terraform_plan
        steps:
          - task: TerraformTask@5
            displayName: terraform_init
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)\envirerment\dev'
              backendServiceArm: 'window-vm'
              backendAzureRmStorageAccountName: 'bigbasketcompany'
              backendAzureRmContainerName: 'big'
              backendAzureRmKey: 'qa.tf'        
          - task: TerraformTask@5
            displayName: terraform_plan
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(System.DefaultWorkingDirectory)\envirerment\dev'
              environmentServiceNameAzureRM: 'window-vm'

  - stage: Scaning_tools
    displayName: Scaning_tools
    dependsOn: terraform_plan
    jobs:
      - job: Scaning_tools
        steps:
          - task: tfsec@1
            inputs:
              version: 'v1.26.0'
              dir: '$(System.DefaultWorkingDirectory)\envirerment\dev'

  - stage: Mannual_validations
    displayName: Mannual_validations 
    pool: server
    dependsOn: Scaning_tools
    jobs:
      - job: Mannual_validations 
        steps:
          - task: ManualValidation@1
            inputs:
              notifyUsers: 'sonupandit@ajayazure21gmail.onmicrosoft.com'
              approvers: 'sonupandit@ajayazure21gmail.onmicrosoft.com'
              onTimeout: 'resume'

